heroku/sf-functions-python

salesforce_functions/__init__.py
salesforce_functions/context.py
salesforce_functions/data_api/__init__.py
salesforce_functions/data_api/exceptions.py
salesforce_functions/data_api/record.py
salesforce_functions/data_api/reference_id.py
salesforce_functions/data_api/unit_of_work.py
salesforce_functions/invocation_event.py
tests/test_data_api.py

- Makes all of the public `data_api` module available from the root of the package, apart from exceptions and `DataAPI` itself. They are excluded to (a) reduce the noise when using IDE auto-completion, (b) (in the case of `DataAPI`) to help prevent accidental direct usage in case users weren't aware of `context.org.data_api`'s pre-configured client.
- Sets explicit `__all__` definitions on all public modules, to prevent imports from leaking into the public API.
GUS-W-12099003.

Adjust the public exports for the `data_api` module

---

invoke.sh
tests/fixtures/data_api/main.py
tests/fixtures/returns_context/main.py
tests/test_app.py
tests/test_cloud_event.py
tests/test_data_api.py
tests/utils.py

All of the existing data API tests are performed using a stand-alone `DataAPI` client, rather than via the pre-configured client provided to functions via `context.org.data_api`.
This new test ensures that:
- the public `context.org.data_api` API exists and exposes the data API as expected
- the client is instantiated correctly in `invoke()`
- the shared `aiohttp` session works correctly in `data_api._execute()` (since that code path is untested in the stand-alone tests, since they intentionally don't pass the optional session).
I have also adjusted the mock `salesforceBaseUrl` and `orgDomainUrl` values to more accurately reflect the difference between them. (The former can be a custom URL that doesn't offer an API endpoint, so the client uses the latter, see GUS-W-11819310 for more …

Add a test for `context.org.data_api`

---

.github/CODEOWNERS
.github/dependabot.yml

For parity with our other repositories.
Also sets myself as the default reviewer for Dependabot PRs, to reduce email notification noise to the rest of the members of the team alias, since our teams have the "Only notify requested team members" option enabled. (This is something we should roll out to our other repositories in the future.)
See:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers
https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team
GUS-W-12073227.

Add a CODEOWNERS file

---

salesforce_functions/context.py
tests/fixtures/data_api/main.py

Since:
- it's always set by the runtime
- if any of the Cloud Event fields required to populate `Org` were missing, the Cloud Event parsing would have failed previously
- making it non-optional avoids the assertion/conditional boilerplate in user functions required to keep linting/type-checkers passing.
Should there ever be event types in the future where the org-related metadata in the Cloud Event are missing, that will require multiple other changes regardless, and can be handled via a major version bump of this package.
GUS-W-12110741.

Make `Context.org` type be non-optional

---

salesforce_functions/data_api/exceptions.py

This was unintentionally omitted in #3.

Mark `SalesforceRestApiError` as publicly exported too

---

salesforce_functions/_internal/cli.py
tests/test_cli.py

The `serve` command now outputs the version of the runtime being used, as well as the configuration of the server (currently this is only the number of workers, since other than host/port which are already output by uvicorn, the number of workers is the only other config option).
The `check` command's output has been made more concise, since the "Checking function..." intro was unnecessary (given the command runs instantly).
GUS-W-12094313.
GUS-W-12206626.

Improve the CLI output for the `serve` and `check` commands

---

pyproject.toml
salesforce_functions/data_api/_requests.py
tests/test_data_api.py
tests/wiremock/mappings/query-with-associated-data.json

This modifies the parsing routine of data api queries to correctly parse result sets that include nested `QueriedRecord` data.
[W-12157953](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001FiOtaYAF/view)

Fix parsing of query with nested object

---

.github/workflows/ci.yml

I've occasionally seen intermittent failures in CI due to the WireMock server not having fully booted before the WireMock tests run.
By moving the WireMock setup earlier in the CI steps order (such that running the non-WireMock tests occurs between the WireMock setup and the actual WireMock tests being run, it should give more time for the server to start.
In addition, I have:
- Switched to the `runner.os` var as suggested in the docs:
https://docs.github.com/en/actions/learn-github-actions/environment-variables#detecting-the-operating-system
- Adjusted the step names, so it is clearer why those steps are skipped when looking at a Windows job in the dashboard.
GUS-W-12212543.

Adjust CI unit-test step order to prevent intermittent failures

---

.github/workflows/ci.yml
.gitignore
pyproject.toml
salesforce_functions/_internal/cli.py
salesforce_functions/_internal/cloud_event.py
salesforce_functions/data_api/__init__.py
salesforce_functions/data_api/_requests.py

Locally, code coverage checking is enabled, but only prints a summary, and does not enforce a threshold, since the common case of testing locally is with the default pytest options, which intentionally do not run the WireMock-requiring tests, so will not achieve full coverage.
In CI however, code coverage is enforced, and is checked by running pytest twice (once for tests that run on all platforms, and again for the WireMock tests), followed by the `coverage report` command.
The `pytest-cov` pytest plugin is used, which is a thin wrapper around the `coverage` Python package.
In the future additional tests will be added to cover some more of the cases currently marked as `# pragma: no cover`.
See:
https://pytest-cov.readthedocs.io
https://coverage.readthedocs.io
GUS-W-12207644.

Enable checking of code coverage

---

tests/test_cli.py

The output of the `sf-functions-python version` command is consumed by the CLI (and in the future by the CNB) and parsed as semver, in order to perform the minimum version check.
This test ensure that the output remains parsable like this in the future, and that some other prefix isn't added to the version stdout, or a non-semver version string (like `X.Y`) isn't used.
GUS-W-12207642.

Test that the version command output can be parsed as semver

---

pyproject.toml

So that the test output is easier to read when tests fail, since the code coverage report is otherwise output right at the end of the log output, requiring scrolling up to see the actual test failures.
GUS-W-12207644.

Skip code coverage report when tests fail

---

pyproject.toml
tests/test_cli.py

When developing locally, `sf run function` can end up connecting to either the IPv4 or IPv6 localhost adapter, depending on the host's OS and hosts file. We recently found that when run locally, the Java Function runtime currently only binds to the IPv4 adapter, causing some clients to fail to connect.
Manual testing showed that this did not affect the current Python implementation, however this adds a test that ensures that doesn't change in the future. (Particularly since it's somewhat dependant on an unintentional side-effect of uvicorns's single-worker implementation).
As an added bonus, this test also adds coverage of:
- the `__main__.py` entrypoint (so we can stop skipping it for coverage)
- running the server outside of `starlette`'s `TestClient` (which tries to emulate the ASGI …

Test the server binds to both the IPv4 and IPv6 localhost adapters

---

README.md

To make the currently published version more discoverable, and to save a few clicks when I (or anyone else) wants to visit PyPI or CI results.
I was going to also add the shields.io badge for listing the supported Python versions, however that appears to be dependant on the PyPI package `classifiers`, rather than using the newer `requires-python` field. We'll add the classifiers later, but until they are set in the published package, the badge would be broken, so I've not added it here.

Add README badges for PyPI and CI

---

.github/workflows/ci.yml
tests/fixtures/template/main.py
tests/fixtures/template/project.toml
tests/test_app.py
tests/test_function_loader.py

This repository's unit/functional tests are very thorough, however they only test the `sf-functions-python` entry point and everything within it.
These new integration tests ensure the `sf-functions-python` command works as expected when used via the Python CNB or Salesforce CLI, catching potential issues like breaking changes in the subcommand options, mismatched expectations over host/port binding, or whether the runtime works with the CNB's default Python version.
As an added bonus, they also test:
- Building the package as a wheel using Hatch's CLI (which is otherwise only performed when publishing to PyPI).
- Using the package from `site-packages` (the unit tests use editable mode, so run from the source directory).
- Using the package without the development-only dependencies …

Add integration testing in CI using the CNB and Salesforce CLI

---

pyproject.toml

Which will cause it to output (informational only, sadly) messages about any redundant `# pylint: disable ...` annotations in the codebase.
https://pylint.pycqa.org/en/latest/user_guide/messages/information/useless-suppression.html

Enable the pylint `useless-suppression` rule

---

tests/test_app.py
tests/test_cli.py

Previously the cleanup for a test was not run if the test failed prior to the cleanup step, meaning that later unrelated tests (that depend on traceback output matching a certain string) would fail, causing confusion when debugging.
Now cleanup is run from a `finally` block, to ensure it always occurs.
GUS-W-12256166.

Improve cleanup of the custom `sys.tracebacklimit` in tests

---

pyproject.toml
salesforce_functions/_internal/cloud_event.py
salesforce_functions/_internal/config.py

Previously the `# pragma: no cover` annotation (that tells Coverage.py to ignore missing coverage on that line of code) was being used in cases where we have test coverage, but it's Python version dependant.
The `coverage-conditional-plugin` plugin allows us to only ignore coverage under certain conditions, rather than ignoring it in all environments.
See:
https://github.com/wemake-services/coverage-conditional-plugin
GUS-W-12261444.

Use coverage-conditional-plugin to reduce `no cover` annotations

---

salesforce_functions/data_api/__init__.py
tests/test_data_api.py

There were previously no tests in `test_data_api.py` that used a shared session, even though a shared session is always used when the data API is initialised by the ASGI app.
Whilst there is a test in `test_app.py` that tests the integration of the data API into the ASGI app (and thus uses a shared session), it only tests:
- the happy path (no request exceptions)
- making a single request (so doesn't test session re-use)
- making a standard query that doesn't involve binary data (so doesn't exercise `DataAPI._download_file()`'s session handling)
The new test tests all of these, allowing the removal of a few more coverage exclusion annotations.
GUS-W-12261661.

Add a test for DataAPI's shared session handling

---

README.md

As of this week, Python support is available on the stable release channel of the `sfdx` / `sf` CLIs, so we no longer need to instruct users to switch to the CLI's release candidate channel.
GUS-W-12257127.

Update getting started documentation to use the stable CLI release

---

README.md

It uses the Python versions specified in the PyPI classifiers of the most recently published version.

Add a README badge for supported Python versions

---

README.md

Since `.venv` is slightly more commonly used than `venv`, and is the name referenced by the Python and VSCode documentation:
https://docs.python.org/3/library/venv.html#creating-virtual-environments
https://code.visualstudio.com/docs/python/environments#_create-a-virtual-environment-in-the-terminal

Update suggested virtualenv directory name to `.venv`

---

.github/workflows/ci.yml
pyproject.toml
salesforce_functions/data_api/_requests.py

We already validate the Python type annotations using mypy, however VSCode's Python integration uses the more-strict alternative type-checker pyright.
This has meant on a few occasions type failures only show up in my IDE and not in CI. (As demonstrated by the types that needed fixing as part of this PR.)
To prevent this, we now run pyright in CI. It is run in both the standard full-codebase type checking mode, as well as a mode that verifies the type-completeness of our publicly exported types (which checks the types from a consumer's point of view).
We still run mypy, since many consumers of this package may still be using mypy, so we need to ensure our exported type annotations keep both type checkers satisfied.
https://github.com/microsoft/pyright#installation …

Validate type annotations using pyright too

---

CHANGELOG.md
salesforce_functions/_internal/app.py
salesforce_functions/_internal/cloud_event.py
salesforce_functions/context.py
salesforce_functions/data_api/__init__.py
salesforce_functions/data_api/_requests.py
salesforce_functions/data_api/exceptions.py
salesforce_functions/data_api/record.py
salesforce_functions/data_api/reference_id.py
salesforce_functions/data_api/unit_of_work.py
salesforce_functions/invocation_event.py
tests/fixtures/data_api/main.py
tests/test_data_api.py

In order to reduce the chance of errors at the call-sites, and make them self-documenting.
See:
https://peps.python.org/pep-3102/
https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass
GUS-W-12291595.

Switch to keyword-only arguments for `DataAPI` and all dataclasses

---

salesforce_functions/_internal/logging.py

* Remove TODO comments (since I've now investigated alternative logging approaches for development, and prefer the current configuration).
* Remove the redundant `ExceptionRenderer` (since `ExceptionPrettyPrinter` already handles formatting exceptions if `ExceptionRenderer` wasn't used prior).
* Add some general comments explaining the config.
GUS-W-11870937.

Cleanup structlog configuration

---

salesforce_functions/_internal/app.py
tests/test_app.py

* Prevents the `request.app.state` reference from appearing in the stack trace.
* The explicitly added `Function` type also improves type checking of `app.py` since `request.app.state` always returns the `Any` type.
* Adds a test for the output, which confirms the output doesn't include lots of irrelevant frames (eg those from uvicorn or starlette)
* Renames `invoke` to something more self-documenting (mainly for our benefit, though it also does appear in the user stack trace).
Before:
```
Traceback (most recent call last):
File "/Users/emorley/src/sf-functions-python/salesforce_functions/_internal/app.py", line 86, in invoke
function_result = await request.app.state.function(event, context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

Clean up function exception handling

---

CHANGELOG.md
salesforce_functions/_internal/app.py
tests/test_app.py

Previously only the exception name and string representation would be shown in the case of an unhandled internal runtime error occurring. Now the full stack trace is output too.
GUS-W-12304403.

Output the stack trace if an unhandled internal error occurs

---

tests/test_cli.py
tests/test_main.py

The two ways the Python function runtime's CLI can be started are:
1. Via the `sf-functions-python` script, which is created on package installation thanks to the entry points feature ([docs](https://packaging.python.org/en/latest/specifications/entry-points/)).
2. `python -m salesforce_functions`, which works due to our inclusion of a [`__main__.py`](https://github.com/heroku/sf-functions-python/blob/main/salesforce_functions/__main__.py) file ([docs](https://docs.python.org/3/library/__main__.html#main-py-in-python-packages)).
Whilst both were implicitly tested elsewhere (`-m salesforce_functions` [in one of the CLI tests](https://github.com/heroku/sf-functions-python/blob/bf72379985529f112cdb8ed9bad5a18a80201c06/tests/test_cli.py#L257-L258) due to needing to launch a subprocess; and …

Add tests for `__main__.py` and the entry point script

---

salesforce_functions/_internal/app.py
salesforce_functions/_internal/cli.py
salesforce_functions/_internal/cloud_event.py
tests/test_app.py
tests/test_cli.py

Whilst all of these functions are descendants of the `_internal` module (and so already private), the documentation linters I was trying out do not recognise this, which causes false positives.
Renaming these functions to be private both avoids the above, and makes it clearer when looking at these modules that the functions are not only not publicly exported, but are also only meant for usage within that single file (and not within other internal modules under `_internal.*`).
GUS-W-12366695.

Make all module-internal functions private

---

salesforce_functions/_internal/app.py
salesforce_functions/_internal/logging.py

The publicly exported `get_logger()` is now a function we define, rather than a simple re-export of `structlog.stdlib.get_logger`.
This allows us to:
- Override structlog's docstring (which was previously not very helpful when one didn't know the context of structlog)
- Call `.bind()` before passing the logger back, which means the logger is already instantiated, rather than being a lazy proxy that is only instantiated on first use (which can impact performance depending on how the consumer uses it).
GUS-W-12366719.

Refactor `get_logger`

---

salesforce_functions/_internal/app.py
salesforce_functions/data_api/__init__.py
tests/test_data_api.py

Since:
- being static, they don't actually use `DataAPI`
- we expose `DataAPI` to end users, and whilst these methods were private, they can still be used unless end projects have linting set up to prevent it
- some of the docs linting tools don't handle private static methods well
GUS-W-12384800.

Move private static methods out of `DataAPI`

---

CHANGELOG.md
salesforce_functions/_internal/logging.py
salesforce_functions/data_api/__init__.py
salesforce_functions/data_api/exceptions.py
salesforce_functions/data_api/record.py
salesforce_functions/data_api/reference_id.py
salesforce_functions/data_api/unit_of_work.py
salesforce_functions/invocation_event.py

The docstrings will be used to generate the API reference docs, and are also shown by IDE Python integrations - so I've had another pass through them to make some improvements.
GUS-W-12384800.

Improve docstrings for public APIs

---

CHANGELOG.md
salesforce_functions/_internal/app.py
tests/test_app.py

Adds an `x-extra-info` metadata header to the function HTTP responses, in accordance with the functions spec.
See:
https://github.com/forcedotcom/sf-fx-schema/blob/80f5d7e3fa17f216e8b264b4fcb590136eed3f3e/schema.json#L139-L179
https://salesforce.quip.com/b11BA6yXtuNr#dMbACAM3CVE
And Java/Node.js implementations:
https://github.com/forcedotcom/sf-fx-runtime-nodejs/blob/f63accbd99166b0ee350aeb12eb2fd43494aa4d5/src/server.ts#L238-L252
https://github.com/forcedotcom/sf-fx-runtime-nodejs/blob/f63accbd99166b0ee350aeb12eb2fd43494aa4d5/src/server.ts#L98-L103
https://github.com/forcedotcom/sf-fx-runtime-java/blob/main/sf-fx-runtime-java-runtime/src/main/java/com/salesforce/functions/jvm/runtime/invocation/undertow/ExtraInfo.java
https://github.com/forcedotcom/sf-fx-runtime-java/blob/e51a238e0b658a6 …

Set the `x-extra-info` header on the function HTTP response

---

salesforce_functions/data_api/__init__.py
salesforce_functions/data_api/_requests.py

`base_uri` was used when generating the URL for sub-requests, however it's stripped off in the final URL, so can be replaced by the empty string. This means `CompositeGraphRestApiRequest.url` can start using `org_domain_url` avoiding the confusion reported in W-12304536.
GUS-W-12304536.

Simplify URL generation in `CompositeGraphRestApiRequest`

---

invoke.sh
tests/test_app.py
tests/test_cloud_event.py
tests/utils.py

There are example CloudEvents used in our unit tests and also the development helper script `invoke.sh`, however their contents was incomplete and slightly out of date.
I dumped the contents of a CloudEvent in production (by using a modified version of the runtime package), and have used that to update the CloudEvent fixtures.
GUS-W-11879536.

Update CloudEvent fixtures to more closely match production

---

CHANGELOG.md
salesforce_functions/context.py
salesforce_functions/data_api/__init__.py
salesforce_functions/data_api/record.py
salesforce_functions/data_api/unit_of_work.py
salesforce_functions/invocation_event.py

So that examples are shown in both the IDE tooltips and also the auto-generated docs on `developer.salesforce.com`.
The changes here will be synced with the WIP branch on the docs repository after merge.
GUS-W-12406389.

Add code examples to docstrings for public APIs

---

CHANGELOG.md
salesforce_functions/testing.py
tests/fixtures/template/tests/test_main.py

That contains utilities to help end users test their Python functions.
The changes to the template function fixture will be upstreamed into the actual template in `sf-functions-core` after this merges.
For functions unit testing prior art, see:
https://github.com/heroku/sf-functions-core/blob/main/tmpl/typescript/test/index.test.ts https://github.com/heroku/sf-functions-core/blob/main/tmpl/java/src/test/java/com/example/FunctionTest.java
For more about pytest/pytest-asyncio, see:
https://docs.pytest.org
https://pytest-asyncio.readthedocs.io
And for Python mocking:
https://docs.python.org/3.11/library/unittest.mock.html
GUS-W-11790316.

Add a public `testing` module

---

pyproject.toml
salesforce_functions/_internal/app.py
salesforce_functions/_internal/cli.py
salesforce_functions/_internal/cloud_event.py
tests/test_app.py
tests/utils.py

By renaming `app` to `asgi_app` to fix `redefined-outer-name`, and for `too-many-instance-attributes` moving it to be a line-specific disable instead of being disabled globally.
Also adds `tests/__init__.py` to resolve an import related pylint warning that only shows up in the IDE (after #75), and not the CLI/CI. (Presumably due to the way the IDE plugin runs pylint when linting a single file.)

Enable some globally disabled pylint rules

---

CHANGELOG.md
salesforce_functions/testing.py

Previously the ID was generated at import time and then would not change from one invocation to the next.
Moving the `uuid4()` call out of the function signature also has the benefit that the UUID string doesn't appear in the auto-generated docs, which was causing the generated content to change every time the docs tool was run.
GUS-W-12442238.

Make `mock_event` generate a unique event ID each time it is called

---

CHANGELOG.md

Since it's meant to be in the Keep a Changelog style:
https://keepachangelog.com/en/1.0.0/

Add missing change type headings to CHANGELOG

---

pyproject.toml

Since it's redundant as of Black 23.1.0 (#81):
https://github.com/psf/black/releases/tag/23.1.0

Remove target Python version from the Black configuration

---

.vscode/launch.json

To make debugging the runtime easier.
Now in VSCode, the "Serve Python Function" debug option can be selected when viewing any of the functions fixtures.
The config is identical to that documented in the upcoming Python Functions docs on the Salesforce Developer site.
See:
https://code.visualstudio.com/docs/python/debugging
GUS-W-12482023.

Add a VSCode launch.json configuration

---

salesforce_functions/data_api/__init__.py

Some small refactoring/cleanup split out of the upcoming PR to improve exception handling, in order to reduce the size of that PR.
Part of GUS-W-12304074.

Clean up aiohttp usages in DataAPI

---

CHANGELOG.md
salesforce_functions/data_api/exceptions.py
salesforce_functions/data_api/reference_id.py

The `SalesforceRestApiError`, `InnerSalesforceRestApiError` and `ReferenceId` data API classes were missing docstrings on their class attributes, which results in `pdoc3` auto-generating a confusing description, eg:
```
* `id: str`
Return an attribute of instance, which is of type owner.
```
Now, the explicitly set docstrings are shown instead.
In addition, the order of the exceptions in `data_api.exceptions` has been adjusted, so that the exceptions are displayed in the docs in a more intuitive order (base class first etc).
GUS-W-12442866.

Add docstrings to the data API class attributes missing them

---

CHANGELOG.md
salesforce_functions/data_api/__init__.py
salesforce_functions/data_api/_requests.py
salesforce_functions/data_api/exceptions.py
tests/test_data_api.py

* Adds a new `ClientError` exception, which wraps the `aiohttp.ClientError` exception (which can occur in the case of connection errors, timeouts or other unexpected HTTP errors): https://docs.aiohttp.org/en/stable/client_reference.html#client-exceptions
* `MissingIdFieldError` has been renamed to `MissingFieldError` and the name of the missing field is now exposed in the exception value.
* All `DataAPI` exceptions now have suitable string representations, making it easier to diagnose errors seen in function logs.
GUS-W-12299777.
GUS-W-12304074.

Improve `DataAPI` exceptions

---

README.md

Since it's now redundant, as the scaffold/template function generated by `sf generate function --language python` now includes a `.gitignore` file, as of:
https://github.com/heroku/sf-functions-core/pull/206
GUS-W-12198175.

Remove the `.gitignore` creation step for the getting started guide

---

CHANGELOG.md
salesforce_functions/testing.py

Previously the time was generated at import time and then would not change from one invocation to the next.
Moving the `datetime.today()` call out of the function signature also has the benefit that the datetime string doesn't appear in the auto-generated docs, which was causing the generated content to change every time the docs tool was run.
This same fix was applied to the `id` parameter in #77, and should have been applied to `time` at that point too.
GUS-W-12442238.

Make `mock_event` generate a unique event time each time it is called

---

CHANGELOG.md
salesforce_functions/data_api/__init__.py
tests/wiremock/mappings/composite-graph-create-tree.json
tests/wiremock/mappings/composite-graph-create.json
tests/wiremock/mappings/composite-graph-single-create-error.json
tests/wiremock/mappings/composite-graph-single-delete.json
tests/wiremock/mappings/composite-graph-single-update.json
tests/wiremock/mappings/create-binary-data.json
tests/wiremock/mappings/create-invalid-field.json
tests/wiremock/mappings/create-invalid-picklist-value.json
tests/wiremock/mappings/create-required-field-missing.json
tests/wiremock/mappings/create-unknown-object.json
tests/wiremock/mappings/create.json
tests/wiremock/mappings/delete-already-deleted.json
tests/wiremock/mappings/delete.json
tests/wiremock/mappings/query-binary-data-subsequent-request.json
tests/wiremock/mappings/query-binary-data.json
tests/wiremock/mappings/query-malformed-soql.json
tests/wiremock/mappings/query-unexpected-response.json
tests/wiremock/mappings/query-unknown-column.json
tests/wiremock/mappings/query-with-associated-data.json
tests/wiremock/mappings/query-with-next-records-url-2.json
tests/wiremock/mappings/query-with-next-records-url.json
tests/wiremock/mappings/query-with-subquery.json
tests/wiremock/mappings/query.json
tests/wiremock/mappings/update-binary-data.json
tests/wiremock/mappings/update-invalid-field.json
tests/wiremock/mappings/update-malformed-id.json
tests/wiremock/mappings/update.json

Previously the values for `encoding` and `content-type` were inverted, causing eg:
```
Traceback (most recent call last):
File ".../.venv/lib/python3.10/site-packages/salesforce_functions/_internal/app.py", line 79, in _handle_function_invocation
function_result = await function(event, context)
File ".../functions/hellopython/main.py", line 77, in function
result = await context.org.data_api.commit_unit_of_work(unit_of_work)
File ".../.venv/lib/python3.10/site-packages/salesforce_functions/data_api/__init__.py", line 200, in commit_unit_of_work
return await self._execute(
File ".../.venv/lib/python3.10/site-packages/salesforce_functions/data_api/__init__.py", line 243, in _execute
return await rest_api_request.process_response(response.status, json_body)
File …
```

Fix the content type and body handling of data API requests

---

README.md

So that if the guide is being followed with an existing virtualenv already activated, any existing dependencies (such as the Python functions runtime) are upgraded to pick up recent fixes.

Add `--upgrade` to the getting started guide `pip install` command

---

.github/workflows/ci.yml

The upstream `sf` CLI now lazy-installs some CLI plugins on first use, such as the `plugin-functions` plugin used in CI:
https://github.com/salesforcecli/cli/blob/27cb011aea1b8d50ef93456bb83f52e384d74f98/package.json#L69
This meant that `plugin-functions` was being installed first before the server could start, causing the smoke test retries/timeouts to be used up before the sever had time to boot:
```
...
curl: (7) Failed to connect to localhost port 8080 after 0 ms: Connection refused
Warning: Problem (retrying all errors). Will retry in 1 seconds. 1 retries 
Warning: left.
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8080 after 0 ms: …
```

Fix CI now that plugin-functions is installed on first use
